upstream:
  titer_vg_per_mL:
    type: lognormal
    mean: 200000000000.0
    sd: 50000000000.0
  volume_L:
    type: fixed
    value: 450.0
    units: L
unit_operations:
- name: Harvest
  yield:
    type: beta
    alpha: 31.5
    beta: 3.5
  volume_model:
    concentration_factor:
      type: fixed
      value: 1.0
- name: Clarification
  yield:
    type: beta
    alpha: 31.5
    beta: 3.5
  volume_model:
    concentration_factor:
      type: fixed
      value: 1.0
- name: Affinity Chromatography
  yield:
    type: beta
    alpha: 31.5
    beta: 3.5
  volume_model:
    concentration_factor:
      type: uniform
      low: 2.0
      high: 4.0
- name: UF/DF
  yield:
    type: beta
    alpha: 31.5
    beta: 3.5
  volume_model:
    concentration_factor:
      type: uniform
      low: 5.0
      high: 12.0
- name: Final Formulation
  yield:
    type: beta
    alpha: 31.5
    beta: 3.5
  volume_model:
    target_volume:
      type: uniform
      low: 4.0
      high: 6.0
      units: L
